server:
  build: .
  environment:
    DATABASE_HOST: postgres
    DATABASE_NAME: postgres
    DATABASE_USER: postgres
    DATABASE_PASSWORD: postgres
  links:
    - postgres:postgres

postgres:
  image: postgres:9.4
