#!/usr/bin/env python

import json
import sys
import urllib2

url = 'https://mandrillapp.com/api/1.0/messages/send.json'
to, subject, message = sys.argv[1:4]

message, conf = message.split('--CONFIG JSON--')

conf = json.loads(conf.strip())
api_key = conf['MANDRILL_API_KEY']
from_email = conf['MANDRILL_FROM_EMAIL']
from_name = conf['MANDRILL_FROM_NAME']

message = dict(key=api_key,
               message=dict(
                   subject=subject,
                   text=message,
                   from_email=from_email,
                   from_name=from_name,
                   to=[dict(email=to)]))
urllib2.urlopen(url, json.dumps(message))
